# Generated by Django 3.2.6 on 2021-09-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
                ('emailid', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('adhar_no', models.BigIntegerField()),
                ('Date', models.DateField()),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
