# Generated by Django 3.2.6 on 2021-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
