# Generated by Django 3.2.6 on 2021-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_admin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('purchase_date', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('adharno', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
