# Generated by Django 3.2.6 on 2021-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20210907_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('selectquery', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
