# Generated by Django 3.2.6 on 2021-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('empcode', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('address', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('gender', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('pincode', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('aadhaarno', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('dateofjoining', models.CharField(max_length=50)),
                ('dateofbirth', models.CharField(max_length=50)),
                ('salary', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('username', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('password', models.CharField(blank=True, default='NO NAME', max_length=50)),
            ],
        ),
    ]
