# Generated by Django 3.2.6 on 2021-09-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('address', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('gender', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('pincode', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('aadhaarno', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('dateofjoining', models.DateField()),
                ('dateofbirth', models.DateField()),
                ('salary', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('username', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('password', models.CharField(blank=True, default='NO NAME', max_length=50)),
            ],
        ),
    ]
